apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-food-deployment
  labels:
    app: fast-food
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-food
  template:
    metadata:
      name: fast-food
      labels:
        app: fast-food
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 8.8.8.8     # Google DNS
          - 1.1.1.1     # Cloudflare DNS
      containers:
        - name: fast-food
          image: 897722698720.dkr.ecr.us-east-1.amazonaws.com/fast-food:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "800Mi"
              cpu: "700m"
            limits:
              memory: "800Mi"
              cpu: "700m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: POSTGRES_DATABASE
            - name: POSTGRES_USER
              valueFrom:
                  secretKeyRef:
                    name: secrets
                    key: POSTGRES_ROOT_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                  secretKeyRef:
                      name: secrets
                      key: POSTGRES_ROOT_PASSWORD
            - name: MERCADO_PAGO_ACCESS_TOKEN
              valueFrom:
                  secretKeyRef:
                      name: secrets
                      key: MERCADO_PAGO_ACCESS_TOKEN
            - name: JWT_SECRET_KEY
              valueFrom:
                  secretKeyRef:
                      name: secrets
                      key: JWT_SECRET_KEY
      restartPolicy: Always

      
