apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: fast-food-svc
spec:
  selector:
    app: fast-food
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
