apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name }}
  labels:
    {{- include "fast-food.labels" . | nindent 4 }}
    app: {{.Chart.Name }}
spec:
  replicas: {{.Values.deployment.replicaCount}}
  selector:
    matchLabels:
      app: {{.Chart.Name }}
  template:
    metadata:
      name: {{.Chart.Name }}
      labels:
        app: {{.Chart.Name }}
    spec:
      containers:
        - name: {{.Chart.Name }}
          image: {{ .Values.deployment.image.repository}}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{.Values.deployment.image.pullPolicy}}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.port}}
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: DB_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: DB_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: DB_DATABASE
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secret.name }}
                  key: password
            - name: MERCADO_PAGO_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: fast-food-mercado-pago
                  key: accessToken
      restartPolicy: Always


