{{- range $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
type: Opaque
stringData:
  {{- range $key, $value := $secret.data }}
  {{$key | nindent 2}}: "{{$value}}"
  {{- end}}
{{- end}}

# WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
# Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
